version: '3.8'

services:
  postgres_1:
    image: postgres
    environment:
      POSTGRES_DB: transaction_service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_1_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"    # Redis default port
    volumes:
      - redis_data:/data  # Persist Redis data

volumes:
  postgres_1_data:
  redis_data:
